version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/myProjectForGit
file_exists_behavior: OVERWRITE
hooks: 
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

